
import { Inter } from "next/font/google";
import { Provider } from 'react-redux'; // Import Provider
import { makeStore } from "@/redux/store";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import Header from "@/components/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Recipe radar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const store = makeStore();
  return (
  
    <html lang="en">
        <body className={inter.className}>
          <ReduxProvider>
            <Header></Header>
            {children}
          </ReduxProvider>
          
          </body>
      </html>
   
      
    
  );
}